### PR TITLE
Update toc

### PR DESCRIPTION
**Pull request by HadarH**

### CODE REVIEW

**Comment by maxbridges** [comment]
@HadarH @lwhinson Did this build on staging correctly? Just curious--I think this introduces a tab character into the toc whereas spaces are used elsewhere. The official guidance is to not do that, but if it works, it works.

**Comment by lwhinson** [comment]
@maxbridges It looks ok to me on staging

**Comment by maxbridges** [comment]
@lwhinson I'm actually seeing different files on staging vs. master. NBD--if it breaks, it's easy enough to fix, now.

**Comment by lwhinson** [comment]
@HadarH After production is updated, please check your changes and make sure that nothing is broken. Thanks!

**Pull request merged**
